export const browserCoreExamples = [
  "fluffbuzz browser status",
  "fluffbuzz browser start",
  "fluffbuzz browser stop",
  "fluffbuzz browser tabs",
  "fluffbuzz browser open https://example.com",
  "fluffbuzz browser focus abcd1234",
  "fluffbuzz browser close abcd1234",
  "fluffbuzz browser screenshot",
  "fluffbuzz browser screenshot --full-page",
  "fluffbuzz browser screenshot --ref 12",
  "fluffbuzz browser snapshot",
  "fluffbuzz browser snapshot --format aria --limit 200",
  "fluffbuzz browser snapshot --efficient",
  "fluffbuzz browser snapshot --labels",
];

export const browserActionExamples = [
  "fluffbuzz browser navigate https://example.com",
  "fluffbuzz browser resize 1280 720",
  "fluffbuzz browser click 12 --double",
  'fluffbuzz browser type 23 "hello" --submit',
  "fluffbuzz browser press Enter",
  "fluffbuzz browser hover 44",
  "fluffbuzz browser drag 10 11",
  "fluffbuzz browser select 9 OptionA OptionB",
  "fluffbuzz browser upload /tmp/fluffbuzz/uploads/file.pdf",
  'fluffbuzz browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "fluffbuzz browser dialog --accept",
  'fluffbuzz browser wait --text "Done"',
  "fluffbuzz browser evaluate --fn '(el) => el.textContent' --ref 7",
  "fluffbuzz browser console --level error",
  "fluffbuzz browser pdf",
];
