#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${FLUFFBUZZ_INSTALL_E2E_IMAGE:-${FLUFFBOT_INSTALL_E2E_IMAGE:-fluffbuzz-install-e2e:local}}"
INSTALL_URL="${FLUFFBUZZ_INSTALL_URL:-${FLUFFBOT_INSTALL_URL:-https://fluffbuzz.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
FLUFFBUZZ_E2E_MODELS="${FLUFFBUZZ_E2E_MODELS:-${FLUFFBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e FLUFFBUZZ_INSTALL_URL="$INSTALL_URL" \
  -e FLUFFBUZZ_INSTALL_TAG="${FLUFFBUZZ_INSTALL_TAG:-${FLUFFBOT_INSTALL_TAG:-latest}}" \
  -e FLUFFBUZZ_E2E_MODELS="$FLUFFBUZZ_E2E_MODELS" \
  -e FLUFFBUZZ_INSTALL_E2E_PREVIOUS="${FLUFFBUZZ_INSTALL_E2E_PREVIOUS:-${FLUFFBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e FLUFFBUZZ_INSTALL_E2E_SKIP_PREVIOUS="${FLUFFBUZZ_INSTALL_E2E_SKIP_PREVIOUS:-${FLUFFBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
